#let myLang = "it" // it/en only
#let myName = "Angela Favaro"
#let myMatricola = "2111015"
#let myTitle = "Applicazioni di ML, Clustering e Forecasting, per Campagne Omnicanale in contesto Aziendale."
#let myProf = "Lamberto Ballan"
#let myCompany = "Blue BI SRL"
#let myLocation = "Padova"
#let myAY = "2025-2026"
#let myTime = "Settembre 2026"
#let myTutor = "Alberto Ferrara"
#let myUni = "Università degli studi di Padova"
#let myDepartment = [Dipartimento di Matematica 'Tullio Levi-Civita']
#let myFaculty = "Corso di Laurea in Informatica"
#let myDegree = "Tesi di laurea triennale"
